[2023-02-18T22:14:19.171+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-08T03:39:00+00:00 [queued]>
[2023-02-18T22:14:19.176+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-08T03:39:00+00:00 [queued]>
[2023-02-18T22:14:19.176+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T22:14:19.176+0200] {taskinstance.py:1369} INFO - Starting attempt 2 of 4
[2023-02-18T22:14:19.176+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-18T22:14:19.182+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): format_data_to_avro> on 2023-02-08 03:39:00+00:00
[2023-02-18T22:14:19.186+0200] {standard_task_runner.py:52} INFO - Started process 31479 to run task
[2023-02-18T22:14:19.190+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales2', 'format_data_to_avro', 'scheduled__2023-02-08T03:39:00+00:00', '--job-id', '5040', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/main2.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpvn7w_hft', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpr0cfffe9']
[2023-02-18T22:14:19.191+0200] {standard_task_runner.py:80} INFO - Job 5040: Subtask format_data_to_avro
[2023-02-18T22:14:19.218+0200] {task_command.py:371} INFO - Running <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-08T03:39:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2023-02-18T22:14:19.254+0200] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_process_sales2
AIRFLOW_CTX_TASK_ID=format_data_to_avro
AIRFLOW_CTX_EXECUTION_DATE=2023-02-08T03:39:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-08T03:39:00+00:00
[2023-02-18T22:14:19.258+0200] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/dags/process_sales/main2.py", line 57, in format_data_to_avro
    for d in data['data']
KeyError: 'data'
[2023-02-18T22:14:19.260+0200] {taskinstance.py:1407} INFO - Marking task as UP_FOR_RETRY. dag_id=test_process_sales2, task_id=format_data_to_avro, execution_date=20230208T033900, start_date=20230218T201419, end_date=20230218T201419
[2023-02-18T22:14:19.264+0200] {standard_task_runner.py:92} ERROR - Failed to execute job 5040 for task format_data_to_avro ('data'; 31479)
[2023-02-18T22:14:19.294+0200] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-18T22:14:19.305+0200] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
