[2023-02-19T13:46:43.717+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-09T03:07:00+00:00 [queued]>
[2023-02-19T13:46:43.723+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-09T03:07:00+00:00 [queued]>
[2023-02-19T13:46:43.723+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-19T13:46:43.723+0200] {taskinstance.py:1369} INFO - Starting attempt 3 of 4
[2023-02-19T13:46:43.723+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-19T13:46:43.729+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): format_data_to_avro> on 2023-02-09 03:07:00+00:00
[2023-02-19T13:46:43.733+0200] {standard_task_runner.py:52} INFO - Started process 57699 to run task
[2023-02-19T13:46:43.736+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales2', 'format_data_to_avro', 'scheduled__2023-02-09T03:07:00+00:00', '--job-id', '5293', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/main2.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmppc8ecf9x', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpdw9mlkif']
[2023-02-19T13:46:43.738+0200] {standard_task_runner.py:80} INFO - Job 5293: Subtask format_data_to_avro
[2023-02-19T13:46:43.763+0200] {task_command.py:371} INFO - Running <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-09T03:07:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2023-02-19T13:46:43.800+0200] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_process_sales2
AIRFLOW_CTX_TASK_ID=format_data_to_avro
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T03:07:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-09T03:07:00+00:00
[2023-02-19T13:46:43.803+0200] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/dags/process_sales/main2.py", line 58, in format_data_to_avro
    for d in data['data']
TypeError: list indices must be integers or slices, not str
[2023-02-19T13:46:43.806+0200] {taskinstance.py:1407} INFO - Marking task as UP_FOR_RETRY. dag_id=test_process_sales2, task_id=format_data_to_avro, execution_date=20230209T030700, start_date=20230219T114643, end_date=20230219T114643
[2023-02-19T13:46:43.809+0200] {standard_task_runner.py:92} ERROR - Failed to execute job 5293 for task format_data_to_avro (list indices must be integers or slices, not str; 57699)
[2023-02-19T13:46:43.839+0200] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-19T13:46:43.850+0200] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
