[2023-02-19T13:43:49.513+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-08T03:57:00+00:00 [queued]>
[2023-02-19T13:43:49.518+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-08T03:57:00+00:00 [queued]>
[2023-02-19T13:43:49.518+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-19T13:43:49.518+0200] {taskinstance.py:1369} INFO - Starting attempt 1 of 4
[2023-02-19T13:43:49.518+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-19T13:43:49.524+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): format_data_to_avro> on 2023-02-08 03:57:00+00:00
[2023-02-19T13:43:49.528+0200] {standard_task_runner.py:52} INFO - Started process 56883 to run task
[2023-02-19T13:43:49.532+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales2', 'format_data_to_avro', 'scheduled__2023-02-08T03:57:00+00:00', '--job-id', '5137', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/main2.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpf9it7oiy', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmprgp9ru4l']
[2023-02-19T13:43:49.533+0200] {standard_task_runner.py:80} INFO - Job 5137: Subtask format_data_to_avro
[2023-02-19T13:43:49.558+0200] {task_command.py:371} INFO - Running <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-08T03:57:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2023-02-19T13:43:49.596+0200] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_process_sales2
AIRFLOW_CTX_TASK_ID=format_data_to_avro
AIRFLOW_CTX_EXECUTION_DATE=2023-02-08T03:57:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-08T03:57:00+00:00
[2023-02-19T13:43:49.599+0200] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/dags/process_sales/main2.py", line 58, in format_data_to_avro
    for d in data['data']
TypeError: list indices must be integers or slices, not str
[2023-02-19T13:43:49.602+0200] {taskinstance.py:1407} INFO - Marking task as UP_FOR_RETRY. dag_id=test_process_sales2, task_id=format_data_to_avro, execution_date=20230208T035700, start_date=20230219T114349, end_date=20230219T114349
[2023-02-19T13:43:49.605+0200] {standard_task_runner.py:92} ERROR - Failed to execute job 5137 for task format_data_to_avro (list indices must be integers or slices, not str; 56883)
[2023-02-19T13:43:49.639+0200] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-19T13:43:49.650+0200] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
