[2023-02-10T22:28:36.596+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-09T17:25:00+00:00 [queued]>
[2023-02-10T22:28:36.602+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-09T17:25:00+00:00 [queued]>
[2023-02-10T22:28:36.602+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T22:28:36.602+0200] {taskinstance.py:1369} INFO - Starting attempt 2 of 4
[2023-02-10T22:28:36.602+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-10T22:28:36.608+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): extract_data_from_api> on 2023-01-09 17:25:00+00:00
[2023-02-10T22:28:36.612+0200] {standard_task_runner.py:52} INFO - Started process 9479 to run task
[2023-02-10T22:28:36.615+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales', 'extract_data_from_api', 'scheduled__2023-01-09T17:25:00+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/mainS.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpqmrk9oia', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpmaej095q']
[2023-02-10T22:28:36.617+0200] {standard_task_runner.py:80} INFO - Job 252: Subtask extract_data_from_api
[2023-02-10T22:28:36.645+0200] {task_command.py:371} INFO - Running <TaskInstance: test_process_sales.extract_data_from_api scheduled__2023-01-09T17:25:00+00:00 [running]> on host admins-MacBook-Air-2.local
[2023-02-10T22:28:36.672+0200] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_process_sales
AIRFLOW_CTX_TASK_ID=extract_data_from_api
AIRFLOW_CTX_EXECUTION_DATE=2023-01-09T17:25:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-09T17:25:00+00:00
[2023-02-10T22:28:36.673+0200] {extract_data_from_api.py:40} INFO - Your custom error1
[2023-02-10T22:28:36.673+0200] {extract_data_from_api.py:41} INFO - Your custom error2
[2023-02-10T22:28:36.673+0200] {logging_mixin.py:115} INFO - Your custom error3
[2023-02-10T22:28:36.673+0200] {python.py:173} INFO - Done. Returned value was: None
[2023-02-10T22:28:36.677+0200] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=test_process_sales, task_id=extract_data_from_api, execution_date=20230109T172500, start_date=20230210T202836, end_date=20230210T202836
[2023-02-10T22:28:36.722+0200] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-02-10T22:28:36.735+0200] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
