[2023-02-19T09:52:58.178+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-08T03:44:00+00:00 [queued]>
[2023-02-19T09:52:58.183+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-08T03:44:00+00:00 [queued]>
[2023-02-19T09:52:58.183+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-19T09:52:58.183+0200] {taskinstance.py:1369} INFO - Starting attempt 4 of 4
[2023-02-19T09:52:58.183+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-19T09:52:58.189+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): format_data_to_avro> on 2023-02-08 03:44:00+00:00
[2023-02-19T09:52:58.193+0200] {standard_task_runner.py:52} INFO - Started process 43228 to run task
[2023-02-19T09:52:58.197+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales2', 'format_data_to_avro', 'scheduled__2023-02-08T03:44:00+00:00', '--job-id', '5091', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/main2.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpwu2iucj1', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpdsneq2p0']
[2023-02-19T09:52:58.198+0200] {standard_task_runner.py:80} INFO - Job 5091: Subtask format_data_to_avro
[2023-02-19T09:52:58.224+0200] {task_command.py:371} INFO - Running <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-08T03:44:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2023-02-19T09:52:58.260+0200] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_process_sales2
AIRFLOW_CTX_TASK_ID=format_data_to_avro
AIRFLOW_CTX_EXECUTION_DATE=2023-02-08T03:44:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-08T03:44:00+00:00
[2023-02-19T09:52:58.263+0200] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/dags/process_sales/main2.py", line 57, in format_data_to_avro
    for d in data['data']
KeyError: 'data'
[2023-02-19T09:52:58.267+0200] {taskinstance.py:1407} INFO - Marking task as FAILED. dag_id=test_process_sales2, task_id=format_data_to_avro, execution_date=20230208T034400, start_date=20230219T075258, end_date=20230219T075258
[2023-02-19T09:52:58.272+0200] {standard_task_runner.py:92} ERROR - Failed to execute job 5091 for task format_data_to_avro ('data'; 43228)
[2023-02-19T09:52:58.313+0200] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-19T09:52:58.324+0200] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
