[2023-02-19T13:45:46.813+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-09T03:04:00+00:00 [queued]>
[2023-02-19T13:45:46.819+0200] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-09T03:04:00+00:00 [queued]>
[2023-02-19T13:45:46.819+0200] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2023-02-19T13:45:46.819+0200] {taskinstance.py:1369} INFO - Starting attempt 3 of 4
[2023-02-19T13:45:46.819+0200] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2023-02-19T13:45:46.825+0200] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): format_data_to_avro> on 2023-02-09 03:04:00+00:00
[2023-02-19T13:45:46.829+0200] {standard_task_runner.py:52} INFO - Started process 57421 to run task
[2023-02-19T13:45:46.832+0200] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'test_process_sales2', 'format_data_to_avro', 'scheduled__2023-02-09T03:04:00+00:00', '--job-id', '5242', '--raw', '--subdir', 'DAGS_FOLDER/process_sales/main2.py', '--cfg-path', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpxc2hwur_', '--error-file', '/var/folders/1g/4w5x68gx3d92wgygb97jqbd40000gp/T/tmpqsl1l06t']
[2023-02-19T13:45:46.834+0200] {standard_task_runner.py:80} INFO - Job 5242: Subtask format_data_to_avro
[2023-02-19T13:45:46.859+0200] {task_command.py:371} INFO - Running <TaskInstance: test_process_sales2.format_data_to_avro scheduled__2023-02-09T03:04:00+00:00 [running]> on host 1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa
[2023-02-19T13:45:46.897+0200] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test_process_sales2
AIRFLOW_CTX_TASK_ID=format_data_to_avro
AIRFLOW_CTX_EXECUTION_DATE=2023-02-09T03:04:00+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-02-09T03:04:00+00:00
[2023-02-19T13:45:46.900+0200] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/v.lytvyniuk/Documents/библиотечка/DE online1/git/de_7/lesson_07/dags/process_sales/main2.py", line 58, in format_data_to_avro
    for d in data['data']
TypeError: list indices must be integers or slices, not str
[2023-02-19T13:45:46.903+0200] {taskinstance.py:1407} INFO - Marking task as UP_FOR_RETRY. dag_id=test_process_sales2, task_id=format_data_to_avro, execution_date=20230209T030400, start_date=20230219T114546, end_date=20230219T114546
[2023-02-19T13:45:46.907+0200] {standard_task_runner.py:92} ERROR - Failed to execute job 5242 for task format_data_to_avro (list indices must be integers or slices, not str; 57421)
[2023-02-19T13:45:46.939+0200] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-02-19T13:45:46.950+0200] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
